# Generated by Django 2.0.9 on 2019-12-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='iconos'),
        ),
    ]
